theme: jekyll-theme-minimal
title: Filipe Constantinov Menezes
logo: https://github.com/fmenezes.png
exclude:
  - README.md
description: |
  I am a software engineer currently based in Dublin, Ireland.
  Proud father, dog owner, husband and geek.
author: Filipe Constantinov Menezes
github:
  is_user_page: false
  is_project_page: false
