remote_theme: b2a3e8/jekyll-theme-console
title: Filipe Constantinov Menezes
logo: https://github.com/fmenezes.png
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
author: Filipe Constantinov Menezes
url: https://www.filipemenezes.com
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
header_pages:
  - index.md
style: dark
footer: '<a target="_blank" href="https://twitter.com/fcmenezes87">Twitter</a> <a target="_blank" href="https://github.com/fmenezes">Github</a> <a target="_blank" href="https://linkedin.com/in/fcmenezes">LinkedIn</a>'
